//Defining avatars
export const characters = [
    {
        "sex": "man",
        "faceColor": "#F9C9B6",
        "earSize": "small",
        "eyeStyle": "oval",
        "noseStyle": "short",
        "mouthStyle": "peace",
        "shirtStyle": "short",
        "glassesStyle": "none",
        "hairColor": "#000",
        "hairStyle": "thick",
        "hatStyle": "none",
        "hatColor": "#F48150",
        "eyeBrowStyle": "up",
        "shirtColor": "#77311D",
        "bgColor": "#D2EFF3"
    },
    {
        "sex": "man",
        "faceColor": "#F9C9B6",
        "earSize": "small",
        "eyeStyle": "oval",
        "noseStyle": "round",
        "mouthStyle": "peace",
        "shirtStyle": "polo",
        "glassesStyle": "none",
        "hairColor": "#000",
        "hairStyle": "thick",
        "hatStyle": "none",
        "hatColor": "#506AF4",
        "eyeBrowStyle": "up",
        "shirtColor": "#FC909F",
        "bgColor": "linear-gradient(45deg, #ff1717 0%, #ffd368 100%)"
    },
    {
        "sex": "woman",
        "faceColor": "#F9C9B6",
        "earSize": "small",
        "eyeStyle": "oval",
        "noseStyle": "short",
        "mouthStyle": "peace",
        "shirtStyle": "short",
        "glassesStyle": "none",
        "hairColor": "#FC909F",
        "hairStyle": "womanLong",
        "hatStyle": "none",
        "hatColor": "#F48150",
        "eyeBrowStyle": "upWoman",
        "shirtColor": "#9287FF",
        "bgColor": "#6BD9E9"
    },
    {
        "sex": "woman",
        "faceColor": "#AC6651",
        "earSize": "big",
        "eyeStyle": "oval",
        "noseStyle": "long",
        "mouthStyle": "peace",
        "shirtStyle": "polo",
        "glassesStyle": "none",
        "hairColor": "#F48150",
        "hairStyle": "womanShort",
        "hatStyle": "none",
        "hatColor": "#000",
        "eyeBrowStyle": "up",
        "shirtColor": "#6BD9E9",
        "bgColor": "linear-gradient(45deg, #1729ff 0%, #ff56f7 100%)"
    },
    {
        "sex": "man",
        "faceColor": "#F9C9B6",
        "earSize": "big",
        "eyeStyle": "oval",
        "noseStyle": "long",
        "mouthStyle": "laugh",
        "shirtStyle": "short",
        "glassesStyle": "none",
        "hairColor": "#000",
        "hairStyle": "normal",
        "hatStyle": "none",
        "hatColor": "#000",
        "eyeBrowStyle": "up",
        "shirtColor": "#9287FF",
        "bgColor": "linear-gradient(45deg, #56b5f0 0%, #45ccb5 100%)"
      },
      {
        "sex": "man",
        "faceColor": "#F9C9B6",
        "earSize": "small",
        "eyeStyle": "smile",
        "noseStyle": "long",
        "mouthStyle": "smile",
        "shirtStyle": "hoody",
        "glassesStyle": "none",
        "hairColor": "#000",
        "hairStyle": "normal",
        "hatStyle": "turban",
        "hatColor": "#77311D",
        "eyeBrowStyle": "up",
        "shirtColor": "#F4D150",
        "bgColor": "#FFEBA4"
      },
      {
        "sex": "woman",
        "faceColor": "#AC6651",
        "earSize": "small",
        "eyeStyle": "smile",
        "noseStyle": "round",
        "mouthStyle": "smile",
        "shirtStyle": "hoody",
        "glassesStyle": "none",
        "hairColor": "#F48150",
        "hairStyle": "normal",
        "hatStyle": "beanie",
        "hatColor": "#77311D",
        "eyeBrowStyle": "up",
        "shirtColor": "#F4D150",
        "bgColor": "linear-gradient(45deg, #ff1717 0%, #ffd368 100%)"
      },
      {
        "sex": "man",
        "faceColor": "#F9C9B6",
        "earSize": "big",
        "eyeStyle": "circle",
        "noseStyle": "long",
        "mouthStyle": "laugh",
        "shirtStyle": "polo",
        "glassesStyle": "square",
        "hairColor": "#FC909F",
        "hairStyle": "normal",
        "hatStyle": "none",
        "hatColor": "#D2EFF3",
        "eyeBrowStyle": "up",
        "shirtColor": "#6BD9E9",
        "bgColor": "#F4D150"
      }
];